name = "PolynomialQTT"
uuid = "87f1ea11-1d4d-47cb-b1d1-07788fc25290"
authors = ["Ritter.Marc <Ritter.Marc@physik.uni-muenchen.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
